language: python
python:
  - "3.7"
services:
  - sqlite3
env:
  global:
    DJANGO_SETTINGS_MODULE="backend.settings"
  matrix:
    - DB=sqlite3
install:
  - pip install -q -r requirements.txt
script:
  - python manage.py test
